language: python

python:
  - "3.8"
  - "3.9"

install:
  - pip install coveralls
  - pip install .

before_script:
  - chmod +x tests/kahelo_test.py

script:
  - python tests/kahelo_test.py
  # - coverage run tests/kahelo_test.py abort

after_success:
  - coveralls
